jobs:
  include:
    - language: python
      python: 3.9
      before_script:
        - cd python
      install:
        - pip3 install -r requirements.txt
      script:
        - pytest

    - language: javascript
      node: 16
      before_script:
        - cd javascript
      install:
        - npm i
      script:
        - npm run test
